name: Run the benchmark tests

on:
  workflow_call:
    inputs:
      target:
        required: false
        type: string
        default: Cpp

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Java JDK
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 14
      - name: Setup Python
        uses: actions/setup-python@v2
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Install Python dependencies
        run: pip3 install -r benchmark/runner/requirements.txt      
      - name: Build lfc
        run: |
          ./gradlew buildLfc
      - name: Setup C++ build environment
        run: |
          ./bin/lfc test/Cpp/src/Minimal.lf
          echo "LD_LIBRARY_PATH=$GITHUB_WORKSPACE/test/Cpp/lib" >> $GITHUB_ENV
        if: ${{ inputs.target == 'Cpp' }}
      - name: Set LF_PATH environmental variable
        run: |
          echo "LF_PATH=$GITHUB_WORKSPACE" >> $GITHUB_ENV
      - name: Test C benchmarks
        run: |
          python3 benchmark/runner/run_benchmark.py -m test_mode=True iterations=1 benchmark="glob(*)" target=lf-c,lf-c-unthreaded iterations=1
        if: ${{ inputs.target == 'C' }}
      - name: Test C++ benchmarks
        run: |
          python3 benchmark/runner/run_benchmark.py -m test_mode=True iterations=1 benchmark="glob(*)" target=lf-cpp iterations=1 target.params.extra_args="[--external-runtime-path, ${GITHUB_WORKSPACE}/test/Cpp]"
        if: ${{ inputs.target == 'Cpp' }}
