name: Uclid5-based Verifier Tests

on:
  workflow_call:

env:
  ACTIONS_STEP_DEBUG: TRUE
  ACTIONS_RUNNER_DEBUG: TRUE

jobs:
  run:
    strategy:
      matrix:
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Check out lingua-franca repository
        uses: actions/checkout@v3
      - name: Check out lf-verifer-benchmarks repository
        uses: actions/checkout@v3
        with:
          repository: lsk567/lf-verifer-benchmarks
          path: ./lf-verifer-benchmarks
      - name: Check out Uclid5 repository
        uses: actions/checkout@v3
        with:
          repository: uclid-org/uclid
          ref: 4fd5e566c5f87b052f92e9b23723a85e1c4d8c1c
          path: ./uclid
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'sbt'
      - name: Setup upterm session
        uses: lhotari/action-upterm@v1
      - name: Install Z3 and Uclid5
        run: |
          cd uclid
          ./get-z3-linux.sh
          ./setup-z3-linux.sh
          sbt update clean compile
          sbt universal:packageBin
          cd target/universal/
          unzip uclid-0.9.5.zip
          export PATH="$(pwd)/uclid-0.9.5/bin:$PATH"
          uclid --version
      - name: Run the test script
        run: |
          cd ../lf-verifer-benchmarks
          ./scripts/test-lf-verifier